### ISSUE TITLE
Question about the dimension of mfcc

### ISSUE THREAD

**Issue by PipiZong** [castorini/honk#103]
Hi,

Can you help explain why the time dimension is 101 instead of 100?

**Comment by PipiZong** [comment]
Also the dataset has 65000 samples ( wav files), why the samples you reported in your paper sum to about 27000? Looking forward to your reply.

**Comment by ljj7975** [comment]
First of all, the dimension is 101 instead of 100 because the data is padded to be centered prior to mfcc computation. Details about the computation can be found from [librosa mfcc documentation](https://librosa.github.io/librosa/generated/librosa.feature.melspectrogram.html)

In the dataset of size 65K, I believe there are >30 classes.
In our implementation, we train our model for ten positive classes, one unknown class, and one silence class.
Given each class has about 3K samples, we construct the unknow class by sampling 3K samples of non-positive classes.
Therefore, the number reported in the paper is not equal to the size of the dataset

Let me know if you have more questions.
Otherwise, please close the issue.

**Comment by PipiZong** [comment]
Got it, I missed those details. Thank you!
