### ISSUE TITLE
ONNX models export

### ISSUE THREAD

**Issue by 4p0pt0Z** [castorini/honk#40]
Hi,

I am trying to reproduce the raspberry-pi demo results, however I cannot produce my own onnx models. 

I tried to train a model of my own, and then convert it to onnx using torch.onnx.export. (as the end of first code cell [here](http://pytorch.org/docs/master/onnx.html)). However, this does not work because onnx does not have the _unsqueeze_ operator which is used in both the SpeechModel and SpeechResModel forward functions. I get this warning :

 ONNX export failed on unsqueeze because torch.onnx.symbolic.unsqueeze does not exist

It appears the unsqueeze operator is not yet implemented in onnx, though they seem to be working on it (cf [https://github.com/onnx/onnx/pull/497](https://github.com/onnx/onnx/pull/497)). Did you use a specific branch of onnx or torch.onnx ?

Could you please provide the code you used to generate your onnx models, or indicate how to export a pytorch model to onnx ?

Thank you

**Comment by daemon** [comment]
Hi,

Yes, ONNX doesn't support `unsqueeze`. I had to remove the `unsqueeze` from the model when exporting, and then I made the appropriate modifications to the model in caffe2.

I don't think SpeechResModel can be exported (ONNX limitations), but SpeechModel can.

**Comment by 4p0pt0Z** [comment]
Hi, thanks for your answer.

I don't really understand how you manage to export the models as you describe. Where do you make the modifications to the caffe2 model ?
If possible, could you post a detailed procedure to do this (I am new to caffe2) or ideally post the code you used ?

Thank you

**Comment by daemon** [comment]
The procedure would be as follows:

1. Remove occurrences of `unsqueeze` from `SpeechModel`, as in modifying the model so that it doesn't unsqueeze any dimensions.
2. Use `torch.onnx` to export `SpeechModel`
3. The ONNX file can now be loaded.

By "appropriate modifications to the model in caffe2," I actually meant [changing the input to the model](https://github.com/castorini/honk/blob/master/service.py#L66-L67). Hope this helps.
