### ISSUE TITLE
Input Features Size

### ISSUE THREAD

**Issue by zhanglaplace** [castorini/honk#58]
thank for your great jobs . 
I see the model config in https://github.com/castorini/honk/blob/master/utils/model.py#L367-L400 ，the model input height is 101 ,It's means the input wav is over 1s when the frame is 10ms .why not choose the standard left 23 and right 8 ?

**Comment by daemon** [comment]
Hi, this is a reimplementation of the [TensorFlow](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/speech_commands/) implementation for keyword spotting on the Google Speech Commands (GSC) dataset. My reasoning is that it's because GSC doesn't have alignment data (though it can be heuristically computed) and all the samples are one second long. It should be straightforward to adapt the code to stack 23 frames on the left and 8 on the right.

**Comment by zhanglaplace** [comment]
@daemon thanks for you answer. In my opinion, the label of 100 frames(1s) can be determined (commands or not commands), but the label of 23 frames on the left and 8 on the right seems  to be marked according to the alignment result.
so,If 32 frames only contain a part of the commands, how to label it?

**Comment by daemon** [comment]
One heuristic that'll work with the GSC dataset is to mark contiguous non-silent frames as the label of that audio clip, as determined by some RMS threshold, e.g., if rms(frame i) is greater than some threshold t for an audio file `yes/x.wav`, then frame i is labeled as "yes." Otherwise, it's labeled as a negative. I imagine a smoothed RMS will work better, since the temporal context will be larger -- you'll have to go through the trimmed audio files manually. On datasets other than GSC, you can use full ASR systems or manual annotating to yield frame-level labels.

> so,If 32 frames only contain a part of the commands, how to label it?

I think the diagram would look like this:
```
-23 -22 ... -1 0 1 2 ... 8
               ^          
past         "now" "future"
```
So the label of the entire input would take on the label of frame `0`.

**Comment by daemon** [comment]
If you would like to try a completely different approach, there are also CTC- and transducer-based keyword spotting approaches:
https://arxiv.org/abs/1709.03665
https://arxiv.org/abs/1710.09617

**Comment by zhanglaplace** [comment]
@daemon thanks. i will have a try .
