### ISSUE TITLE
Are there any useable demo in this project ?

### ISSUE THREAD

**Issue by azuredream** [castorini/honk#86]
"python ." is not runnable on any model in the model.zip now. What is the default expected size in server.py , and how can I change it? It seems that many parameters are hard-coded everywhere.

**Comment by daemon** [comment]
> many parameters are hard-coded everywhere

A lot of parameters are specifiable through the command line. If you're referring to [this](https://github.com/castorini/honk/blob/master/utils/model.py#L381), it's because a lot of the model configurations are standard.

It's been a while since I touched the demo code -- I'll look into it more when I get the chance. What error is it giving?

**Comment by azuredream** [comment]
I'm very grateful :D
